

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4

    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml # 설정값

    healthcheck:
      test: curl -f http://localhost:9200 || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - elk
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
      - kb_data:/usr/share/kibana/data
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk
  filebeat:
    image: elastic/filebeat:9.0.3
    user: root
    volumes:
      - ./filebeats/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/usr/share/filebeat/logs:ro

    depends_on:
      - elasticsearch
    command: filebeat -e --strict.perms=false
    networks:
      - elk
  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    ports:
        - "5044:5044"
        - "9600:9600"

    depends_on:
      elasticsearch:
        condition: service_healthy

    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    networks:
      - elk
networks:
  elk:
    driver: bridge
volumes: 
  kb_data:
  esdata: