global:
  scrape_interval: 15s #메트릭 수집 인터벌
  evaluation_interval: 15s #메트릭 평가 인터벌

scrape_configs:
  - job_name: "prometheus_metrics"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8091"] # Traefik 메트릭 수집 포트

  - job_name: "fastapi"
    static_configs:
      - targets: ["fastapi:8000"] # FastAPI에서 /metrics 노출해야 작동
