global:
  scrape_interval: 15s #메트릭 수집 인터벌
  evaluation_interval: 15s #메트릭 평가 인터벌

scrape_configs:
  - job_name: "prometheus_metrics"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8091"] # Traefik 메트릭 수집 포트

  - job_name: "fastapi"
    static_configs:
      - targets: ["fastapi:8000"] # FastAPI에서 /metrics 노출해야 작동

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb_exporter:9216"]

  - job_name: "qdrant"
    static_configs:
      - targets: ["qdrant:6333"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis_exporter:9121"]

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq_exporter:9419"]

  - job_name: "celery"
    static_configs:
      - targets: ["celery_exporter:9808"]
